import { Flashcard } from '@/types/flashcard';

export const FUNCTIONAL_ENGLISH_FLASHCARDS: Flashcard[] = [
  // --- COOKING & PASSION ---
  { id: 551, category: 'ielts', sub: 'Cooking', question: "Do you enjoy cooking? Why or why not?" },
  { id: 552, category: 'ielts', sub: 'Cooking', question: "Who usually does the cooking in your home?" },
  { id: 553, category: 'ielts', sub: 'Cooking', question: "What was the last meal you cooked for yourself?" },
  { id: 574, category: 'ielts', sub: 'Passion', question: "If money was not an issue, what would you spend your life doing?" },
  { id: 577, category: 'ielts', sub: 'Passion', question: "Who is someone you admire because of their dedication to their work?" },

  // --- MENTALITY & PERSONAL ---
  { id: 558, category: 'ielts', sub: 'Mentality', question: "How do you stay positive when things go wrong?" },
  { id: 581, category: 'ielts', sub: 'Mentality', question: "How do you handle stress when you have a very long to-do list?" },
  { id: 582, category: 'ielts', sub: 'Mentality', question: "What does 'success' mean to you personally?" },
  { id: 555, category: 'ielts', sub: 'Introduction', question: "Could you tell me your full name and where you are from?" },
  { id: 556, category: 'ielts', sub: 'Introduction', question: "How would your friends describe your personality?" },

  // --- HOTEL BOOKING ---
  { id: 560, category: 'ielts', sub: 'Hotel Booking', question: "I'd like to book a room for three nights. What is your nightly rate?" },
  { id: 588, category: 'ielts', sub: 'Hotel Booking', question: "Is there a shuttle service from the airport to the hotel?" },
  { id: 590, category: 'ielts', sub: 'Hotel Booking', question: "Can I leave my luggage here for a few hours after I check out?" },
  { id: 592, category: 'ielts', sub: 'Hotel Booking', question: "The air conditioning in my room isn't working; could you send someone to check it?" },
  { id: 594, category: 'ielts', sub: 'Hotel Booking', question: "What time is the latest I can check out without extra charges?" },

  // --- IMMIGRATION & TRAVEL ---
  { id: 563, category: 'ielts', sub: 'Immigration', question: "What is the purpose of your visit to this country?" },
  { id: 564, category: 'ielts', sub: 'Immigration', question: "How long do you plan to stay, and where will you be residing?" },
  { id: 596, category: 'ielts', sub: 'Immigration', question: "Do you have any items to declare, such as food or electronics?" },
  { id: 597, category: 'ielts', sub: 'Immigration', question: "How much currency are you carrying with you today?" },
  { id: 600, category: 'ielts', sub: 'Immigration', question: "Can I see your hotel reservation or invitation letter?" },

  // --- RESTAURANT ---
  { id: 566, category: 'ielts', sub: 'Restaurant', question: "Could we have a table for two by the window, please?" },
  { id: 568, category: 'ielts', sub: 'Restaurant', question: "I have a food allergy; can this dish be made without nuts?" },
  { id: 602, category: 'ielts', sub: 'Restaurant', question: "Do you have any vegetarian or vegan options available?" },
  { id: 606, category: 'ielts', sub: 'Restaurant', question: "Excuse me, I ordered my steak medium-rare, but this is well-done." },
  { id: 608, category: 'ielts', sub: 'Restaurant', question: "Is service charge included in the bill, or should I leave a tip?" },

  // --- DAILY ROUTINE & HEALTH ---
  { id: 609, category: 'ielts', sub: 'Daily Routine', question: "What is the most productive hour of your day?" },
  { id: 611, category: 'ielts', sub: 'Daily Routine', question: "How much sleep do you need to feel fully rested?" },
  { id: 621, category: 'ielts', sub: 'Health', question: "How do you stay active when you have to sit at a desk all day?" },
  { id: 623, category: 'ielts', sub: 'Health', question: "What is your favorite way to decompress after a long shift?" },
  { "id": 574, "category": "ielts", "sub": "Passion", "question": "If money was not an issue, what would you spend your life doing?" },
  { "id": 575, "category": "ielts", "sub": "Passion", "question": "What is a skill you’ve always wanted to learn but haven't started yet?" },
  { "id": 576, "category": "ielts", "sub": "Passion", "question": "Do you prefer hobbies that are creative or hobbies that are physical?" },
  { "id": 577, "category": "ielts", "sub": "Passion", "question": "Who is someone you admire because of their dedication to their work?" },
  { "id": 578, "category": "ielts", "sub": "Passion", "question": "What is the most rewarding thing about your current project or hobby?" },
  { "id": 579, "category": "ielts", "sub": "Passion", "question": "How do you find time for your passions during a busy work week?" },
  { "id": 580, "category": "ielts", "sub": "Passion", "question": "Is it better to have one deep passion or many small interests?" },

  { "id": 581, "category": "ielts", "sub": "Mentality", "question": "How do you handle stress when you have a very long to-do list?" },
  { "id": 582, "category": "ielts", "sub": "Mentality", "question": "What does 'success' mean to you personally?" },
  { "id": 583, "category": "ielts", "sub": "Mentality", "question": "Do you prefer to plan everything in advance or go with the flow?" },
  { "id": 584, "category": "ielts", "sub": "Mentality", "question": "What is the best piece of advice you have ever received?" },
  { "id": 585, "category": "ielts", "sub": "Mentality", "question": "How do you react when someone gives you unexpected criticism?" },
  { "id": 586, "category": "ielts", "sub": "Mentality", "question": "Do you think it's important to step out of your comfort zone often?" },
  { "id": 587, "category": "ielts", "sub": "Mentality", "question": "How do you stay motivated when learning a difficult new language?" },

  { "id": 588, "category": "ielts", "sub": "Hotel Booking", "question": "Is there a shuttle service from the airport to the hotel?" },
  { "id": 589, "category": "ielts", "sub": "Hotel Booking", "question": "I have a reservation under the name 'John Smith'. Is the room ready?" },
  { "id": 590, "category": "ielts", "sub": "Hotel Booking", "question": "Can I leave my luggage here for a few hours after I check out?" },
  { "id": 591, "category": "ielts", "sub": "Hotel Booking", "question": "Does the room have a safe for my valuables?" },
  { "id": 592, "category": "ielts", "sub": "Hotel Booking", "question": "The air conditioning in my room isn't working; could you send someone to check it?" },
  { "id": 593, "category": "ielts", "sub": "Hotel Booking", "question": "Could I have some extra towels and a bottle of water sent to my room?" },
  { "id": 594, "category": "ielts", "sub": "Hotel Booking", "question": "What time is the latest I can check out without extra charges?" },

  { "id": 595, "category": "ielts", "sub": "Immigration", "question": "Are you traveling alone or with family members?" },
  { "id": 596, "category": "ielts", "sub": "Immigration", "question": "Do you have any items to declare, such as food or electronics?" },
  { "id": 597, "category": "ielts", "sub": "Immigration", "question": "How much currency are you carrying with you today?" },
  { "id": 598, "category": "ielts", "sub": "Immigration", "question": "Is this your first time visiting this country?" },
  { "id": 599, "category": "ielts", "sub": "Immigration", "question": "What is your occupation back in your home country?" },
  { "id": 600, "category": "ielts", "sub": "Immigration", "question": "Can I see your hotel reservation or invitation letter?" },
  { "id": 601, "category": "ielts", "sub": "Immigration", "question": "Do you have a return ticket booked?" },

  { "id": 602, "category": "ielts", "sub": "Restaurant", "question": "Do you have any vegetarian or vegan options available?" },
  { "id": 603, "category": "ielts", "sub": "Restaurant", "question": "Is there a long wait for a table of four?" },
  { "id": 604, "category": "ielts", "sub": "Restaurant", "question": "Could we see the dessert menu, please?" },
  { "id": 605, "category": "ielts", "sub": "Restaurant", "question": "What are the ingredients in this specific dish?" },
  { "id": 606, "category": "ielts", "sub": "Restaurant", "question": "Excuse me, I ordered my steak medium-rare, but this is well-done." },
  { "id": 607, "category": "ielts", "sub": "Restaurant", "question": "Could we have some more water and napkins for the table?" },
  { "id": 608, "category": "ielts", "sub": "Restaurant", "question": "Is service charge included in the bill, or should I leave a tip?" },

  { "id": 609, "category": "ielts", "sub": "Daily Routine", "question": "What is the most productive hour of your day?" },
  { "id": 610, "category": "ielts", "sub": "Daily Routine", "question": "Do you listen to music or podcasts during your commute?" },
  { "id": 611, "category": "ielts", "sub": "Daily Routine", "question": "How much sleep do you need to feel fully rested?" },
  { "id": 612, "category": "ielts", "sub": "Social", "question": "What is the best way to make new friends in a city you just moved to?" },
  { "id": 613, "category": "ielts", "sub": "Social", "question": "Do you enjoy attending large parties or small gatherings more?" },
  { "id": 614, "category": "ielts", "sub": "Travel", "question": "Would you rather travel to a snowy mountain or a tropical beach?" },
  { "id": 615, "category": "ielts", "sub": "Travel", "question": "What is the most essential item in your suitcase when you travel?" },
  { "id": 616, "category": "ielts", "sub": "Future", "question": "What is one thing you hope to achieve by the end of this year?" },
  { "id": 617, "category": "ielts", "sub": "Future", "question": "If you could live anywhere in the world, where would it be?" },
  { "id": 618, "category": "ielts", "sub": "Shopping", "question": "I’m looking for a gift for a friend; do you have any suggestions?" },
  { "id": 619, "category": "ielts", "sub": "Shopping", "question": "Can I return this item if it doesn't fit or if I change my mind?" },
  { "id": 620, "category": "ielts", "sub": "Shopping", "question": "Is there a discount if I buy more than one of these?" },
  { "id": 621, "category": "ielts", "sub": "Health", "question": "How do you stay active when you have to sit at a desk all day?" },
  { "id": 622, "category": "ielts", "sub": "Health", "question": "Do you prefer home-cooked meals or healthy takeout options?" },
  { "id": 623, "category": "ielts", "sub": "Health", "question": "What is your favorite way to decompress after a long shift?" },
  { "id": 551, "category": "ielts", "sub": "Cooking", "question": "Do you enjoy cooking? Why or why not?" },
  { "id": 552, "category": "ielts", "sub": "Cooking", "question": "Who usually does the cooking in your home?" },
  { "id": 553, "category": "ielts", "sub": "Cooking", "question": "What was the last meal you cooked for yourself?" },
  { "id": 554, "category": "ielts", "sub": "Cooking", "question": "Is it important for children to learn how to cook at school?" },

  { "id": 555, "category": "ielts", "sub": "Introduction", "question": "Could you tell me your full name and where you are from?" },
  { "id": 556, "category": "ielts", "sub": "Introduction", "question": "How would your friends describe your personality?" },
  { "id": 557, "category": "ielts", "sub": "Passion", "question": "What is something you are truly passionate about?" },
  { "id": 558, "category": "ielts", "sub": "Mentality", "question": "How do you stay positive when things go wrong?" },
  { "id": 559, "category": "ielts", "sub": "Mentality", "question": "Do you consider yourself an introvert or an extrovert?" },

  { "id": 560, "category": "ielts", "sub": "Hotel Booking", "question": "I'd like to book a room for three nights. What is your nightly rate?" },
  { "id": 561, "category": "ielts", "sub": "Hotel Booking", "question": "Does the room come with breakfast and free Wi-Fi?" },
  { "id": 562, "category": "ielts", "sub": "Hotel Booking", "question": "Is it possible to have an early check-in or a late check-out?" },

  { "id": 563, "category": "ielts", "sub": "Immigration", "question": "What is the purpose of your visit to this country?" },
  { "id": 564, "category": "ielts", "sub": "Immigration", "question": "How long do you plan to stay, and where will you be residing?" },
  { "id": 565, "category": "ielts", "sub": "Immigration", "question": "Can you provide proof of your return flight and travel insurance?" },

  { "id": 566, "category": "ielts", "sub": "Restaurant", "question": "Could we have a table for two by the window, please?" },
  { "id": 567, "category": "ielts", "sub": "Restaurant", "question": "What do you recommend from the menu today?" },
  { "id": 568, "category": "ielts", "sub": "Restaurant", "question": "I have a food allergy; can this dish be made without nuts?" },
  { "id": 569, "category": "ielts", "sub": "Restaurant", "question": "Could we have the bill, please? Do you accept credit cards?" },

  { "id": 570, "category": "ielts", "sub": "Shopping", "question": "Do you have this shirt in a medium size and a different color?" },
  { "id": 571, "category": "ielts", "sub": "Shopping", "question": "Where are the fitting rooms located?" },
  { "id": 572, "category": "ielts", "sub": "Daily Life", "question": "How do you usually get to work or school every morning?" },
  { "id": 573, "category": "ielts", "sub": "Daily Life", "question": "What is the first thing you do when you wake up?" },
  { "id": 501, "category": "ielts", "sub": "Work/Study", "question": "What are you studying at the moment?" },
  { "id": 502, "category": "ielts", "sub": "Work/Study", "question": "What is the most difficult part of your job?" },
  { "id": 503, "category": "ielts", "sub": "Work/Study", "question": "Is there anything you would like to change about your workplace?" },
  { "id": 504, "category": "ielts", "sub": "Hometown", "question": "What is the most interesting part of your hometown?" },
  { "id": 505, "category": "ielts", "sub": "Hometown", "question": "How has your hometown changed since you were a child?" },
  { "id": 506, "category": "ielts", "sub": "Daily Routine", "question": "What is your favorite part of the day?" },
  { "id": 507, "category": "ielts", "sub": "Daily Routine", "question": "Do you think it is important to have a daily routine?" },
  { "id": 508, "category": "ielts", "sub": "Technology", "question": "How often do you use social media?" },
  { "id": 509, "category": "ielts", "sub": "Technology", "question": "Do you think people spend too much time on their phones these days?" },
  { "id": 510, "category": "ielts", "sub": "Leisure", "question": "What do you usually do on your weekends?" },

  { "id": 511, "category": "ielts", "sub": "Food", "question": "What is your favorite type of cuisine?" },
  { "id": 512, "category": "ielts", "sub": "Food", "question": "Do you prefer eating at home or at a restaurant?" },
  { "id": 513, "category": "ielts", "sub": "Travel", "question": "What is the most beautiful place you have ever visited?" },
  { "id": 514, "category": "ielts", "sub": "Travel", "question": "Do you prefer traveling alone or with a group of friends?" },
  { "id": 515, "category": "ielts", "sub": "Environment", "question": "What are the main environmental problems in your country?" },
  { "id": 516, "category": "ielts", "sub": "Environment", "question": "How can individuals help protect the environment?" },
  { "id": 517, "category": "ielts", "sub": "Education", "question": "Do you think children should start learning a second language at a young age?" },
  { "id": 518, "category": "ielts", "sub": "Education", "question": "What qualities make a good teacher?" },
  { "id": 519, "category": "ielts", "sub": "Friends", "question": "How much time do you spend with your friends?" },
  { "id": 520, "category": "ielts", "sub": "Friends", "question": "What do you look for in a good friend?" },

  { "id": 521, "category": "ielts", "sub": "Art", "question": "Are you interested in art?" },
  { "id": 522, "category": "ielts", "sub": "Art", "question": "Have you ever been to an art gallery?" },
  { "id": 523, "category": "ielts", "sub": "Weather", "question": "What kind of weather do you like the most?" },
  { "id": 524, "category": "ielts", "sub": "Weather", "question": "Does the weather ever affect your mood?" },
  { "id": 525, "category": "ielts", "sub": "Hobby", "question": "What hobbies were popular in your country when you were a child?" },
  { "id": 526, "category": "ielts", "sub": "Hobby", "question": "Is it important for people to have a hobby?" },
  { "id": 527, "category": "ielts", "sub": "Sports", "question": "What is the most popular sport in your country?" },
  { "id": 528, "category": "ielts", "sub": "Sports", "question": "Do you prefer watching sports or playing them?" },
  { "id": 529, "category": "ielts", "sub": "Shopping", "question": "Do you enjoy shopping for clothes?" },
  { "id": 530, "category": "ielts", "sub": "Shopping", "question": "Is online shopping better than going to physical stores?" },

  { "id": 531, "category": "ielts", "sub": "Music", "question": "What kind of music do you listen to when you are stressed?" },
  { "id": 532, "category": "ielts", "sub": "Music", "question": "Have you ever learned to play a musical instrument?" },
  { "id": 533, "category": "ielts", "sub": "Transport", "question": "What is the most common form of transport in your city?" },
  { "id": 534, "category": "ielts", "sub": "Transport", "question": "Should public transport be free for everyone?" },
  { "id": 535, "category": "ielts", "sub": "History", "question": "Are you interested in learning about the history of your country?" },
  { "id": 536, "category": "ielts", "sub": "History", "question": "What historical event has shaped the world the most?" },
  { "id": 537, "category": "ielts", "sub": "Dreams", "question": "Do you often remember your dreams?" },
  { "id": 538, "category": "ielts", "sub": "Dreams", "question": "Do you think dreams have any special meaning?" },
  { "id": 539, "category": "ielts", "sub": "Animals", "question": "Are you a fan of wild animals?" },
  { "id": 540, "category": "ielts", "sub": "Animals", "question": "Should animals be kept in zoos?" },

  { "id": 541, "category": "ielts", "sub": "Future", "question": "What are your plans for the next few years?" },
  { "id": 542, "category": "ielts", "sub": "Future", "question": "How do you think the world will change in the next 50 years?" },
  { "id": 543, "category": "ielts", "sub": "Happiness", "question": "What makes you feel truly happy?" },
  { "id": 544, "category": "ielts", "sub": "Happiness", "question": "Can money buy happiness?" },
  { "id": 545, "category": "ielts", "sub": "Culture", "question": "What is the most famous festival in your country?" },
  { "id": 546, "category": "ielts", "sub": "Culture", "question": "Is it important to maintain traditional culture?" },
  { "id": 547, "category": "ielts", "sub": "Cities", "question": "Do you prefer living in a big city or the countryside?" },
  { "id": 548, "category": "ielts", "sub": "Cities", "question": "What are the disadvantages of living in a crowded city?" },
  { "id": 549, "category": "ielts", "sub": "Ambition", "question": "What was your dream job when you were a child?" },
  { "id": 550, "category": "ielts", "sub": "Ambition", "question": "Is it better to be ambitious or to be satisfied with what you have?" }


];