import { Flashcard } from '@/types/flashcard';

export const PROGRAMMER_FLASHCARDS: Flashcard[] = [
    { "id": 301, "category": "rn", "sub": "Architecture", "question": "What is the React Native Bridge and why is it a bottleneck?" },
  { "id": 302, "category": "rn", "sub": "Architecture", "question": "Explain the New Architecture: What are JSI, Fabric, and TurboModules?" },
  { "id": 303, "category": "rn", "sub": "Architecture", "question": "How does the Hermes engine improve app start-up time (TTI)?" },
  { "id": 304, "category": "rn", "sub": "Architecture", "question": "What is the difference between the JS Thread, UI Thread, and Shadow Thread?" },
  { "id": 305, "category": "rn", "sub": "Architecture", "question": "What is Yoga, and how does it translate Flexbox to native layouts?" },
  { "id": 306, "category": "rn", "sub": "Architecture", "question": "What is JSI (JavaScript Interface) and how does it allow synchronous calls?" },
  { "id": 307, "category": "rn", "sub": "Architecture", "question": "Explain Bridgeless Mode in React Native 0.73+." },
  { "id": 308, "category": "rn", "sub": "Architecture", "question": "How does Fabric improve the rendering performance of UI components?" },
  { "id": 309, "category": "rn", "sub": "Architecture", "question": "What is the role of Codegen in the New Architecture?" },
  { "id": 310, "category": "rn", "sub": "Architecture", "question": "How does React Native handle the 'Double Bridge' problem with animations?" },

  { "id": 311, "category": "rn", "sub": "Performance", "question": "How do you identify a Memory Leak in a React Native app?" },
  { "id": 312, "category": "rn", "sub": "Performance", "question": "Why is InteractionManager.runAfterInteractions useful for smooth UI transitions?" },
  { "id": 313, "category": "rn", "sub": "Performance", "question": "How would you optimize a FlatList with 5,000+ items?" },
  { "id": 314, "category": "rn", "sub": "Performance", "question": "What is the benefit of FlashList over the standard FlatList?" },
  { "id": 315, "category": "rn", "sub": "Performance", "question": "Explain the purpose of initialNumToRender and maxToRenderPerBatch in lists." },
  { "id": 316, "category": "rn", "sub": "Performance", "question": "How do you use the 'Profiler' to find components causing slow re-renders?" },
  { "id": 317, "category": "rn", "sub": "Performance", "question": "Why should you avoid using anonymous functions inside the render/return block?" },
  { "id": 318, "category": "rn", "sub": "Performance", "question": "What is the impact of console.log statements on production performance?" },
  { "id": 319, "category": "rn", "sub": "Performance", "question": "How do you reduce the JS Bundle size for a production build?" },
  { "id": 320, "category": "rn", "sub": "Performance", "question": "What is the difference between useMemo and useCallback in RN performance?" },

  { "id": 321, "category": "rn", "sub": "State", "question": "When would you choose Zustand over Redux Toolkit in 2026?" },
  { "id": 322, "category": "rn", "sub": "State", "question": "How does the Context API compare to Redux regarding re-rendering behavior?" },
  { "id": 323, "category": "rn", "sub": "State", "question": "What is React Query and why is it preferred for server-state management?" },
  { "id": 324, "category": "rn", "sub": "State", "question": "How do you persist state across app restarts using MMKV?" },
  { "id": 325, "category": "rn", "sub": "State", "question": "Explain the 'Offline Sync' pattern for mobile form submissions." },
  { "id": 326, "category": "rn", "sub": "State", "question": "What is the difference between useState and useRef for tracking non-UI values?" },
  { "id": 327, "category": "rn", "sub": "State", "question": "How do you handle 'Prop Drilling' without using a global state library?" },
  { "id": 328, "category": "rn", "sub": "State", "question": "Explain how to use useLayoutEffect to prevent UI flickering in RN." },
  { "id": 329, "category": "rn", "sub": "State", "question": "How do you create a custom hook to detect network connectivity status?" },
  { "id": 330, "category": "rn", "sub": "State", "question": "What is useImperativeHandle and when should you use it with Ref?" },

  { "id": 331, "category": "rn", "sub": "Styling", "question": "How do you handle different screen densities using PixelRatio?" },
  { "id": 332, "category": "rn", "sub": "Styling", "question": "What is the difference between 'flex: 1' in RN vs standard Web CSS?" },
  { "id": 333, "category": "rn", "sub": "Styling", "question": "How do you implement Dynamic Dark Mode in React Native?" },
  { "id": 334, "category": "rn", "sub": "Styling", "question": "What are Safe Area Insets and why are they critical for 'Notch' devices?" },
  { "id": 335, "category": "rn", "sub": "Styling", "question": "How do you create a responsive layout that works on both iPhone and Tablets?" },
  { "id": 336, "category": "rn", "sub": "Styling", "question": "How do you handle RTL (Right-to-Left) layouts for specific languages?" },
  { "id": 337, "category": "rn", "sub": "Styling", "question": "What is the benefit of using aspectRatio over fixed width/height?" },
  { "id": 338, "category": "rn", "sub": "Styling", "question": "How do you conditionally apply styles based on Platform.OS (iOS vs Android)?" },
  { "id": 339, "category": "rn", "sub": "Styling", "question": "Explain the difference in Z-Index behavior between Android and iOS." },
  { "id": 340, "category": "rn", "sub": "Styling", "question": "Why is StyleSheet.create preferred over inline style objects?" },

  { "id": 341, "category": "rn", "sub": "Native", "question": "How do you create a Native Module for iOS using Swift?" },
  { "id": 342, "category": "rn", "sub": "Native", "question": "How do you create a Native Module for Android using Kotlin?" },
  { "id": 343, "category": "rn", "sub": "Native", "question": "What is the difference between Expo Managed Workflow and Bare Workflow?" },
  { "id": 344, "category": "rn", "sub": "Native", "question": "What is an Expo Config Plugin and when do you need one?" },
  { "id": 345, "category": "rn", "sub": "Native", "question": "Explain the purpose of the Podfile and Podfile.lock in iOS." },
  { "id": 346, "category": "rn", "sub": "Native", "question": "What is Auto-linking and how does it work under the hood?" },
  { "id": 347, "category": "rn", "sub": "Native", "question": "How do you pass data from Native code back to JavaScript using Events?" },
  { "id": 348, "category": "rn", "sub": "Native", "question": "What is the 'Prebuild' command in Expo and what does it do?" },
  { "id": 349, "category": "rn", "sub": "Native", "question": "How do you link a 3rd-party C++ library to a React Native project?" },
  { "id": 350, "category": "rn", "sub": "Native", "question": "What are JSI Host Objects and how do they replace the old bridge maps?" },

  { "id": 351, "category": "rn", "sub": "Animations", "question": "Why is useNativeDriver: true essential for the standard Animated API?" },
  { "id": 352, "category": "rn", "sub": "Animations", "question": "What are Shared Values in Reanimated 3 and how do they work?" },
  { "id": 353, "category": "rn", "sub": "Animations", "question": "How do you use Skia in React Native for high-performance 2D graphics?" },
  { "id": 354, "category": "rn", "sub": "Animations", "question": "What is the difference between Layout Animations and Frame-based animations?" },
  { "id": 355, "category": "rn", "sub": "Animations", "question": "How do you handle complex gestures with React Native Gesture Handler?" },
  { "id": 356, "category": "rn", "sub": "Animations", "question": "How do you animate a 'Header' that shrinks as the user scrolls?" },
  { "id": 357, "category": "rn", "sub": "Animations", "question": "What is a PanResponder and when would you still use it today?" },
  { "id": 358, "category": "rn", "sub": "Animations", "question": "How do you use Lottie for vector animations in React Native?" },
  { "id": 359, "category": "rn", "sub": "Animations", "question": "Explain Worklets in the context of Reanimated." },
  { "id": 360, "category": "rn", "sub": "Animations", "question": "How do you create a 'Parallax' effect in a ScrollView?" },

  { "id": 361, "category": "rn", "sub": "Navigation", "question": "What is the difference between Stack, Tab, and Drawer navigators?" },
  { "id": 362, "category": "rn", "sub": "Navigation", "question": "How do you handle Deep Linking and Universal Links in React Navigation?" },
  { "id": 363, "category": "rn", "sub": "Navigation", "question": "What is the Navigation Container and why is it at the root?" },
  { "id": 364, "category": "rn", "sub": "Navigation", "question": "How do you prevent a user from going back after a successful login?" },
  { "id": 365, "category": "rn", "sub": "Navigation", "question": "Explain how to use useFocusEffect instead of useEffect for screens." },
  { "id": 366, "category": "rn", "sub": "Navigation", "question": "How do you implement Nested Navigation structures?" },
  { "id": 367, "category": "rn", "sub": "Navigation", "question": "How do you pass parameters to a screen without making them stale?" },
  { "id": 368, "category": "rn", "sub": "Navigation", "question": "How do you track screen views for Analytics using Navigation state?" },
  { "id": 369, "category": "rn", "sub": "Navigation", "question": "What is the benefit of using Native Stack over the JS-based Stack?" },
  { "id": 370, "category": "rn", "sub": "Navigation", "question": "How do you create a custom reusable Header for all screens?" },

  { "id": 371, "category": "rn", "sub": "Deployment", "question": "What is a Phased Release (iOS) and a Staged Rollout (Android)?" },
  { "id": 372, "category": "rn", "sub": "Deployment", "question": "How do you handle App Store rejection for 'Sign in with Apple' requirements?" },
  { "id": 373, "category": "rn", "sub": "Deployment", "question": "What is Code Push and what are the Apple/Google legal limitations?" },
  { "id": 374, "category": "rn", "sub": "Deployment", "question": "How do you manage App Versioning vs Build Numbers in a team?" },
  { "id": 375, "category": "rn", "sub": "Deployment", "question": "What are Privacy Manifests in iOS 17+ and why do they matter?" },
  { "id": 376, "category": "rn", "sub": "Deployment", "question": "Explain the difference between a Debug APK and a Signed AAB bundle." },
  { "id": 377, "category": "rn", "sub": "Deployment", "question": "What is Google Play Data Safety and how do you declare SDK usage?" },
  { "id": 378, "category": "rn", "sub": "Deployment", "question": "How do you use TestFlight for external beta testing?" },
  { "id": 379, "category": "rn", "sub": "Deployment", "question": "What is Fastlane and how does it automate store uploads?" },
  { "id": 380, "category": "rn", "sub": "Deployment", "question": "How do you handle In-App Purchases (IAP) logic and receipts?" },

  { "id": 381, "category": "rn", "sub": "Testing", "question": "What is the difference between Jest (Unit) and Detox (E2E) testing?" },
  { "id": 382, "category": "rn", "sub": "Testing", "question": "How do you mock a native module like AsyncStorage in Jest?" },
  { "id": 383, "category": "rn", "sub": "Testing", "question": "What is React Native Testing Library and why use it over Enzyme?" },
  { "id": 384, "category": "rn", "sub": "Testing", "question": "How do you debug Native Crashes using Xcode and Android Studio?" },
  { "id": 385, "category": "rn", "sub": "Testing", "question": "What are Source Maps and how do you use them with Sentry?" },
  { "id": 386, "category": "rn", "sub": "Testing", "question": "How do you simulate 'Low Memory' or 'No Network' in an emulator?" },
  { "id": 387, "category": "rn", "sub": "Testing", "question": "What is a Snapshot Test and when is it actually useful?" },
  { "id": 388, "category": "rn", "sub": "Testing", "question": "How do you debug Layout issues using the Flipper Layout Inspector?" },
  { "id": 389, "category": "rn", "sub": "Testing", "question": "How do you test a component that uses custom hooks?" },
  { "id": 390, "category": "rn", "sub": "Testing", "question": "Explain the Red-Green-Refactor cycle in TDD for mobile." },

  { "id": 391, "category": "rn", "sub": "Security", "question": "How do you securely store sensitive API tokens in React Native?" },
  { "id": 392, "category": "rn", "sub": "Security", "question": "What is SSL Pinning and why is it used for fintech apps?" },
  { "id": 393, "category": "rn", "sub": "Security", "question": "How do you implement Biometric Auth (FaceID/Fingerprint) in RN?" },
  { "id": 394, "category": "rn", "sub": "Security", "question": "What is the difference between iOS Keychain and Android Keystore?" },
  { "id": 395, "category": "rn", "sub": "Security", "question": "How do you prevent 'Man-in-the-Middle' attacks in mobile apps?" },
  { "id": 396, "category": "rn", "sub": "Security", "question": "Explain JWT refresh token logic to keep a user logged in safely." },
  { "id": 397, "category": "rn", "sub": "Security", "question": "What is Code Obfuscation (Proguard/DexGuard) and do you need it?" },
  { "id": 398, "category": "rn", "sub": "Security", "question": "How do you handle Certificate Pinning updates without breaking the app?" },
  { "id": 399, "category": "rn", "sub": "Security", "question": "How do you protect your app against running on Rooted/Jailbroken devices?" },
  { "id": 400, "category": "rn", "sub": "Security", "question": "What is the best way to handle App Permissions (Camera/Location) in 2026?" },
  // --- APP STORES & DEPLOYMENT ---
{ id: 271, category: "appstore", question: "What is a 'Phased Release' (iOS) or 'Staged Rollout' (Android) and why is it critical for updates?" },
{ id: 272, category: "appstore", question: "What are the common reasons for Apple App Store rejections regarding 'Guideline 4.0 - Design'?" },
{ id: 273, category: "appstore", question: "How do you handle 'Code Push' updates versus full Store updates? When is Code Push illegal?" },
{ id: 274, category: "appstore", question: "What is the difference between 'App Store Connect' and 'Google Play Console' regarding 'Review Time' in 2026?" },
{ id: 275, category: "appstore", question: "Explain how to handle 'Breaking Changes' in an API when 30% of your users are still on an old app version." },
{ id: 276, category: "appstore", question: "What is 'TestFlight' and 'Firebase App Distribution'? How do they differ in a professional CI/CD pipeline?" },
{ id: 277, category: "appstore", question: "How do you manage 'App Bundle' (.aab) vs 'APK' and why did Google move to AAB?" },
{ id: 278, category: "appstore", question: "What is 'Data Safety' (Play Store) and 'Privacy Manifest' (App Store)? How do you declare third-party SDK tracking?" },

{ id: 201, category: "mentoring", question: "How do you provide constructive feedback to a junior developer whose code quality is consistently low?" },
  { id: 202, category: "mentoring", question: "Describe your process for onboarding a new engineer to your technical stack." },
  { id: 203, category: "mentoring", question: "How do you encourage a mentee to solve a problem themselves instead of giving them the answer?" },
  { id: 204, category: "mentoring", question: "What do you do if a junior developer repeatedly makes the same mistake after you've corrected them?" },
  { id: 205, category: "mentoring", question: "How do you identify which learning opportunities would be most valuable for different team members?" },
  { id: 206, category: "mentoring", question: "How do you balance your own coding tasks with the time required to mentor others?" },
  { id: 207, category: "mentoring", question: "What techniques do you use to explain complex system architecture to someone less experienced?" },
  { id: 208, category: "mentoring", question: "How do you help a team member who is struggling with 'Imposter Syndrome'?" },

  // --- leadership ---
  { id: 221, category: "leadership", question: "How do you handle a situation where two senior engineers fundamentally disagree on a technical approach?" },
  { id: 222, category: "leadership", question: "Tell me about a time you had to lead a team through a high-pressure production outage." },
  { id: 223, category: "leadership", question: "How do you convince stakeholders to pause feature development to pay down technical debt?" },
  { id: 224, category: "leadership", question: "What is your approach to managing a developer who is underperforming?" },
  { id: 225, category: "leadership", question: "How do you maintain team morale during a period of shifting company priorities or layoffs?" },
  { id: 226, category: "leadership", question: "Describe a time you led by example to change a team's culture or workflow." },
  { id: 227, category: "leadership", question: "How do you ensure that quiet team members have their voices heard during architectural discussions?" },
  { id: 228, category: "leadership", question: "How do you define 'Engineering Excellence' for your team?" },

  // --- personal & GROWTH ---
  { id: 241, category: "personal", question: "Where do you see your technical career path in 5 years? (Individual Contributor vs. Management)" },
  { id: 242, category: "personal", question: "What is the biggest professional mistake you’ve made, and what did you learn from it?" },
  { id: 243, category: "personal", question: "How do you manage work-life balance when a project deadline is approaching?" },
  { id: 244, category: "personal", question: "What are your 3 biggest strengths as a developer, and what is one area you are currently improving?" },
  { id: 245, category: "personal", question: "Describe a non-technical hobby that has made you a better programmer." },
  { id: 246, category: "personal", question: "What motivates you to keep coding every day besides the salary?" },
  { id: 247, category: "personal", question: "How do you handle 'burnout' or periods of low motivation?" },
  { id: 248, category: "personal", question: "What kind of work environment allows you to do your best work?" },

  { id: 1, category: "frontend", question: "What is the difference between Virtual DOM and Shadow DOM?" },
  { id: 2, category: "frontend", question: "How do you optimize a React app that has too many re-renders?" },
  { id: 3, category: "frontend", question: "Explain the 'Event Loop' in JavaScript." },
  { id: 4, category: "frontend", question: "What is the difference between 'debouncing' and 'throttling'?" },
  { id: 5, category: "frontend", question: "How does 'Next.js' handle Image Optimization?" },
  { id: 6, category: "frontend", question: "What are 'Closures' and provide a real-world use case?" },
  { id: 7, category: "frontend", question: "Difference between 'SSR' (Server Side Rendering) and 'SSG' (Static Site Generation)?" },
  { id: 8, category: "frontend", question: "What is 'Hoisting' in JavaScript?" },
  { id: 9, category: "frontend", question: "Explain 'Hydration' in the context of Next.js." },
  { id: 10,category: "frontend", question: "How to prevent Layout Shift (CLS) on a web page?" },

  // --- BACKEND & DATABASE ---
  { id: 51, category: "backend", question: "What is the difference between SQL and NoSQL?" },
  { id: 52, category: "backend", question: "Explain 'ACID' properties in database transactions." },
  { id: 53, category: "backend", question: "How does 'JWT' (JSON Web Token) authentication work?" },
  { id: 54, category: "backend", question: "What is a 'Deadlock' and how can you prevent it?" },
  { id: 55, category: "backend", question: "Explain the difference between 'PUT' and 'PATCH' in REST APIs." },
  { id: 56, category: "backend", question: "What is 'Database Indexing' and why does it make queries faster?" },
  { id: 57, category: "backend", question: "What is 'Rate Limiting' and how would you implement it?" },
  { id: 58, category: "backend", question: "Explain 'Horizontal' vs 'Vertical' scaling." },
  { id: 59, category: "backend", question: "What is the 'N+1 Query Problem' and how do you solve it?" },
  { id: 60, category: "backend", question: "How do 'WebSockets' differ from traditional 'HTTP' requests?" },

  // --- CS FUNDAMENTALS & ALGORITHMS ---
  { id: 101, category: "algorithms", question: "What is 'Big O' notation and why is it important?" },
  { id: 102, category: "algorithms", question: "Difference between a 'Stack' and a 'Queue'?" },
  { id: 103, category: "algorithms", question: "How does a 'Binary Search' algorithm work?" },
  { id: 104, category: "algorithms", question: "Explain the 'Time Complexity' of Quick Sort vs Merge Sort." },
  { id: 105, category: "algorithms", question: "What is a 'Hash Table' and how does it handle collisions?" },
  { id: 106, category: "algorithms", question: "Explain the difference between 'Recursion' and 'Iteration'." },
  { id: 107, category: "algorithms", question: "What is a 'Linked List' and when is it better than an Array?" },
  { id: 108, category: "algorithms", question: "Describe 'Breadth-First Search' (BFS) vs 'Depth-First Search' (DFS)." },
  { id: 109, category: "algorithms", question: "What is 'Dynamic Programming'?" },
  { id: 110, category: "algorithms", question: "How do you detect a cycle in a Linked List?" },

  // --- BEHAVIORAL ---
  { id: 151, category: "behavioral", question: "Tell me about a time you had a technical disagreement with a teammate." },
  { id: 152, category: "behavioral", question: "How do you handle a situation where you are behind on a deadline?" },
  { id: 153, category: "behavioral", question: "What is the most difficult bug you have ever fixed?" },
  { id: 154, category: "behavioral", question: "How do you keep your technical skills up to date?" },
  { id: 155, category: "behavioral", question: "Describe a project you are most proud of and your specific role in it." },
  { id: 156, category: "behavioral", question: "What do you do when you don't know the answer to a technical problem?" },
  { id: 157, category: "behavioral", question: "Tell me about a time you had to learn a new technology very quickly." },
  { id: 158, category: "behavioral", question: "How do you handle constructive criticism during code reviews?" },
  { id: 159, category: "behavioral", question: "What is your process for debugging a complex production issue?" },
  { id: 160, category: "behavioral", question: "Why should we hire you over other candidates with similar skills?" },
]